name: Reload Caddy Proxy

on:
  workflow_run:
    workflows: ["Deploy Stack to Swarm"]
    types:
      - completed

jobs:
  reload:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Restart Caddy
        run: |
          echo "🔄 Restarting Caddy..."
          docker service update --force caddy_caddy