services:
  postgresSQL:
    image: postgres:17-alpine
    networks:
    - homelab
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=AllOfTheStars+1
    - PGDATA=/var/lib/postgresql/data
    volumes:
    - /home/doc/projects/unraid-appdata/postgres:/var/lib/postgresql/data
    ports:
    - target: 5432
      published: 5434
      mode: host
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      replicas: 1

networks:
  homelab:
    external: true
