services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    networks:
    - homelab
    ports:
    - 9696:9696
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    volumes:
    - /home/doc/projects/swarm-data/appdata/prowlarr:/config
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9696/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 1

networks:
  homelab:
    external: true 
