services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    networks:
    - homelab
    ports:
    - 7878:7878
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    volumes:
    - /home/doc/projects/unraid-appdata/radarr:/config
    - /home/doc/projects/data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7878/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      replicas: 1

networks:
  homelab:
    external: true
