services:
  n8n:
    image: n8nio/n8n:latest
    ports:
    - 5678:5678
    networks:
    - homelab
    environment:
    - N8N_HOST=n8n.bitfrost.me
    - N8N_PORT=5678
    - N8N_PROTOCOL=https
    - N8N_RUNNERS_ENABLED=true
    - WEBHOOK_URL=https://n8n.bitfrost.me/
    - TZ=America/New_York
    volumes:
    - /home/doc/swarm/data/n8n:/home/node/.n8n
    - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 1
      placement:
        constraints:
        - node.hostname == p0
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

networks:
  homelab:
    external: true
