services:
  nginx-pm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8099:80' 
      - '4434:443'
      - '81:81'
    environment:
      TZ: "America/New_York"
    volumes:
      - /home/doc/projects/swarm-data/appdata/nginx-pm/data:/data
      - /home/doc/projects/swarm-data/appdata/nginx-pm/le:/etc/letsencrypt
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == p1
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
    networks:
      - homelab
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:81"]
      interval: 1m30s
      timeout: 10s
      retries: 3
networks:
  homelab:
    external: true